openapi: 3.0.2

info:
  title: Boilerplate for Flask REST API
  version: 1.0.0
  description: Boilerplate for Flask REST APIs
  contact:
      name: Amil Osmanli 
      email: osmanli.ao@gmail.com

servers:
  - url: http://127.0.0.1:5000/api
    description: Development server

paths:
  /greetings:
    get:
      tags:
        - Greetings
      summary: Returns greeting
      description: Sample enpoint that returns greeting message
      parameters:
        - $ref: '#/components/parameters/NameParam'
      responses:
        '200':
          $ref: '#/components/responses/Greeting'
        default:
          description: |
            error occurred - see status code and problem object for more information
          content:
            application/problem+json:
              schema:
                $ref: 'https://zalando.github.io/problem/schema.yaml#/Problem'
components:
  parameters:
    NameParam:
      name: name
      in: query
      required: false
      description: Optional parameter to make enpoint to say your name
      schema:
        type: string
  responses:
    Greeting:
      description: a greeting
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Greeting'
  schemas:
    Greeting:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: "James Bond"

